install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V
  - git submodule update --init --recursive

build: false

branches:
  except:
    - staging.tmp
    - trying.tmp

environment:
  global:
    RUST_BACKTRACE: full

    # Temporary fix.
    # See <https://github.com/rust-lang-nursery/rand/commit/bb78689>
    RUSTUP_USE_HYPER: 1
    CARGO_HTTP_CHECK_REVOKE: false

test_script:
  - cargo build --verbose --all
  - cargo doc   --verbose --all --no-deps

  - cargo test  --verbose --all
